version: 0.2
os: Linux
files:
 - source: /
   destination: /home/ec2-user
hooks:
 ApplicationStop:
   - location: scripts/stop_server.sh
     timeout: 300
     runas: root
 BeforeInstall:
   - location: scripts/before_install.sh
     timeout: 300
     runas: root
 AfterInstall:
   - location: scripts/start_server.sh
     timeout: 300
     runas: root
 ApplicationStart:
   - location: scripts/application_start.sh
     timeout: 300
     runas: root
 ValidateService:
   - location: scripts/validate_service.sh
     timeout: 300
     runas: root